routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home','HomeController@index')->name('home');
Route::post('/tasks-store/{meeting_id?}','TaskController@store')->name('tasks-store');
Route::post('/subjects-store/{meeting_id?}','SubjectController@store')->name('subjects-store');
Route::get('tasks/done/{id}', 'TaskController@done')->name('done');
Route::get('tasks/donelate/{id}', 'TaskController@donelate')->name('donelate');
Route::get('tasks/discussed/{id}','TaskController@discussed')->name('discussed');
Route::resource('/employees','EmployeesController')->middleware('auth');
Route::get('/MyMeetings','MeetingController@indexMy')->name('MyMeetings');

Route::resource('/meetings','MeetingController')->middleware('auth');
Route::get('/sendemail', 'SendEmailController@index')->name('sendemail');
Route::post('/sendemail/send', 'SendEmailController@send');

Route::resource('/dashboards','DashboardController')->middleware('auth');

Route::resource('/tasks','TaskController')->except(['store']);
Route::resource('/subjects','SubjectController')->except(['store']);
Route::get('tasks/{meeting_id}','TaskController@store');
Route::get('meetings/{organization_id}','MeetingController@store');
Route::get('subjects/{meeting_id}','SubjectController@store');

Route::get('tasks/meetingTasks/{meeting_id}','TaskController@meetingTasks')->name('meetingTasks');
Route::get('/newOne', function () { return view('newOne');})->name('newOne');

Route::get('/moveTo/{id?}','SubjectController@moveTo')->name('moveTo');
Route::get('/moveToThisMeeting/{id?}/{subject_id}','SubjectController@moveToThisMeeting')->name('moveToThisMeeting');

app/Meeting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meeting extends Model
{
    protected $fillable =[
        'title','meeting_start','meeting_end' ];

        public function user(){
            return $this->hasMany('App\User');
        }
    
        public function meeting(){
            return $this->hasMany('App\Meeting');
        }
}

app/Http/Controllers/MeetingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Meeting;
use App\User;
use App\Invite;
use App\Task;
use App\Subject;
use App\Organization;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Meetings\CreatMeetingRequests;
use App\Http\Requests\Meetings\UpdateMeetingsRequest;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;

class MeetingController extends Controller
{
    
    public function index()
    {
        $id_user = Auth::id();
        $user= User::where('id', $id_user)->firstOrFail();
        $organization_id=$user->organization_id;
        //return view('meetings.index')->with ('meetings',Meeting::all());
        return view('meetings.index')->with ('meetings',Meeting::where('organization_id',$organization_id)->get());
    }
    public function indexMy(){
    
        $id_user = Auth::id();
        $myMettings=Invite::where('user_id', $id_user)->get();
        //return view('meetings.index')->with ('meetings',Meeting::all());
        return view('meetings.myMetting')->with ('meetings',$myMettings);
    }
    

    
    public function create()
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to create new meeting..");
        }
        $id = Auth::id();
        $user= User::find($id);
        $org_id= $user->organization_id; 
        $users = User::where('organization_id',$org_id)->get();

        return view('meetings.create',compact('users'));   
     }

   
    public function store(Request $request)
    {

        $id_user = Auth::id();
        $user= User::where('id', $id_user)->firstOrFail();
        $organization_id=$user->organization_id;
        $meeting=new Meeting();
        $id = Auth::id();
        $meeting->user_id=$id;
        $meeting->organization_id= $organization_id;
        $meeting->title=$request->title;
        $meeting->meeting_start=$request->meeting_start;
        $meeting->meeting_end=$request->meeting_end;
        $meeting->save();

        foreach($request->inviteds as $invited){
            Invite::create([
                'meeting_id'=>$meeting->id,
                'user_id'=>$invited,
            ]);
        }

     
        return redirect(route('meetings.index'));  
    }

   
    public function show($id)
    {
        //
    }

    
    public function edit(Meeting $meeting)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to edit the meeting..");
        }
        $id = Auth::id();
        $user= User::find($id);
        $org_id= $user->organization_id; 
        $users = User::where('organization_id',$org_id)->get();

        return view('meetings.create')->with('meeting', $meeting)->with('users', $users);
    }
    
    public function update(UpdateMeetingsRequest $request,Meeting $meeting)
    {
        $meeting->title=$request->title;
        $meeting->save();
        return redirect(route('meetings.index')); 
    }

    
    public function destroy(Meeting $meeting)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to edit the meeting..");
        }
        $meeting->delete();
        return redirect(route('meetings.index'));
    }
}

resources/views/meetings/create.blade.php
@extends('layouts.app')
@section('content')

<div class ="card card -default">
    <div class="card-header">
    {{isset($meeting)? "Edit Meeting Category" :"Create Meeting Category" }}
    </div>
    <div class="card-body">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul class="list-group">
            @foreach ($errors->all() as $error)
                <li class="list-group-item text-danger">
                {{ $error }}
                </li>
            @endforeach
        </ul>
    </div>
    @endif

   <form method="POST" action="{{isset($meeting)?route('meetings.update',$meeting->id) : route('meetings.store')}}">
     {{csrf_field()}}
     @if(isset($meeting))
      @method('PUT')
     @endif 
      <div class="form-group">
       <label for="title">Title</label>
       <input type="text" id="title" class="form-control" name="title" value="{{isset($meeting) ? $meeting->title :''}}">
      </div> 
      <div class="form-group">
       <label for="meeting_start">Meeting Start </label>
       <input type="datetime-local" id="meeting_start" class="form-control" name="meeting_start" value="{{isset($meeting) ? $meeting->meeting_start :''}}" required>
      </div>    

      <div class="form-group">
       <label for="meeting_end">Meeting End </label>
       <input type="datetime-local" id="meeting_end" class="form-control" name="meeting_end" value="{{isset($meeting) ? $meeting->meeting_end :''}}"required>
      </div> 

      <div class="form-group">
      <label for="choose">choose usets that you want to invite (please press Ctrl and mark the name)</label>

         <select  class="form-control" data-role="tagsinput"  name="inviteds[]" multiple="multiple">
                                            <option value="{{Auth::user()->id}}" selected>me</option>
                                    
                                    @foreach($users as $user)
                                            @if($user->organization_id==Auth::user()->organization_id && $user->id!=Auth::user()->id)                            
                                                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                                            @endif
                                     @endforeach
                                    </select>
      </div>

      <div class="form-group">
       <button class="btn btn-success">
       {{isset($meeting)?'Update Meeting' : 'Add Meeting'}}
       </button>
      </div>
     </form>
   </div>
</div>    
@endsection

resources/views/meetings/index.blade.php
@extends('layouts.app')
@section('content')

@if(!empty($successMsg))
  <div class="alert alert-success"> {{ $successMsg }}</div>
@endif
<div class ="d-flex justify-content-end mb-2">
@cannot('participant')
    <a href ="{{route('meetings.create')}}" class="btn btn-success">Add New Meeting</a>
@endcannot  
</div>

<div class ="card card -default">
    <div class="card-header">meeting</div>
     <div class = "card-body">
      <table class="table">
       <thead>
        <th>Meeting Title</th>
        <th>Meeting ID</th>
        <th>Seating times</th>
        <th></th>
        
       </thead>
       <tbody>
        @foreach($meetings as $meeting)
         <tr>
         <td><a href ="{{route('meetingTasks',$meeting->id)}}">{{$meeting->title}}</a></td>
          <td>{{$meeting->id}}</td>
          <td>{{$meeting->meeting_start}}</td>
          <td>
           <a href ="{{route('meetings.edit',$meeting->id)}}" class="btn btn-info btn-sm">Edit</a>
           <button class="btn btn-danger btn-sm" onclick="handleDelete({{$meeting->id}})">Delete</button>
          </td>
         </tr>
        @endforeach 
       </tbody>
      </table>
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <form action="" method="POST" id=deleteMeetingForm>
                @csrf
                @method('DELETE')
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Meeting</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p class="text-center text-bold">
                        Are you sure you want to delete this meeting?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go Back</button>
                    <button type="submit" class="btn btn-danger">Yes, Delete</button>
                </div>
                </div>
            </form>
            </div>
            </div>
     </div>   
</div>
@endsection

@section('scripts')
 <script>
  function handleDelete(id){
      var form = document.getElementById("deleteMeetingForm");
      form.action= 'meetings/'+ id; 
      $('#deleteModal').modal('show')
  }
 </script>
@endsection

resources/views/meetings/moveTo.blade.php
@extends('layouts.app')
@section('content')



<div class ="card card -default">
    <div class="card-header">meeting</div>
     <div class = "card-body">
      <table class="table">
       <thead>
        <th>to which meeting do you want to move the subject?</th>
       
        <th></th>
        
       </thead>
       <tbody>
        @foreach($meetings as $meeting)
         <tr>
         <td><a href ="{{route('moveToThisMeeting',[$meeting->id,$subject_id])}}">{{$meeting->title}}</a></td>
        @endforeach 
       </tbody>
      </table>
      
@endsection

@section('scripts')
 <script>
  function handleDelete(id){
      var form = document.getElementById("deleteMeetingForm");
      form.action= 'meetings/'+ id; 
      $('#deleteModal').modal('show')
  }
 </script>
@endsection

resources/views/meetings/myMetting.blade.php
@extends('layouts.app')
@section('content')



<div class ="card card -default">
     <div class = "card-body">
      <table class="table">
       <thead>
        <th>Meeting Id</th>
        <th></th>
        
       </thead>
       <tbody>
        @foreach($meetings as $meeting)
         <tr>
         <td><a href ="{{route('meetingTasks',$meeting->id)}}">{{$meeting->meeting_id}}</a></td>
         </tr>
        @endforeach 
       
</div>
@endsection

@section('scripts')
 <script>
  function handleDelete(id){
      var form = document.getElementById("deleteMeetingForm");
      form.action= 'meetings/'+ id; 
      $('#deleteModal').modal('show')
  }
 </script>
@endsection