routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home','HomeController@index')->name('home');
Route::post('/tasks-store/{meeting_id?}','TaskController@store')->name('tasks-store');
Route::post('/subjects-store/{meeting_id?}','SubjectController@store')->name('subjects-store');
Route::get('tasks/done/{id}', 'TaskController@done')->name('done');
Route::get('tasks/donelate/{id}', 'TaskController@donelate')->name('donelate');
Route::get('tasks/discussed/{id}','TaskController@discussed')->name('discussed');
Route::resource('/employees','EmployeesController')->middleware('auth');
Route::get('/MyMeetings','MeetingController@indexMy')->name('MyMeetings');

Route::resource('/meetings','MeetingController')->middleware('auth');
Route::get('/sendemail', 'SendEmailController@index')->name('sendemail');
Route::post('/sendemail/send', 'SendEmailController@send');

Route::resource('/dashboards','DashboardController')->middleware('auth');

Route::resource('/tasks','TaskController')->except(['store']);
Route::resource('/subjects','SubjectController')->except(['store']);
Route::get('tasks/{meeting_id}','TaskController@store');
Route::get('meetings/{organization_id}','MeetingController@store');
Route::get('subjects/{meeting_id}','SubjectController@store');

Route::get('tasks/meetingTasks/{meeting_id}','TaskController@meetingTasks')->name('meetingTasks');
Route::get('/newOne', function () { return view('newOne');})->name('newOne');

Route::get('/moveTo/{id?}','SubjectController@moveTo')->name('moveTo');
Route::get('/moveToThisMeeting/{id?}/{subject_id}','SubjectController@moveToThisMeeting')->name('moveToThisMeeting');

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    protected $fillable =[
        'time_start','time_end','description','status'
    ];
    public function user(){
        return $this->belongsTo('App\User');
    }

    public function meeting(){
        return $this->belongsTo('App\Meeting');
    }

}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Meeting;
use App\User;
use App\Task;
use App\Subject;
use App\Organization;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Subjects\CreatSubjectRequest;
use App\Http\Requests\Subjects\UpdateSubjectsRequest;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Gate;



class SubjectController extends Controller
{
    
    public function index()
    {
        return view('subjects.index')->with ('subjects',Subject::all());
    }

  
    public function create(Request $request)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to create new subjecs..");
        }
        $meeting_id = $request->get('meeting_id');
        return view('subjects.create')->with('meeting_id', $meeting_id);
    }
    public function moveTo($subject_id)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to create new subjecs..");
        }
        $subject = Subject::where('id',$subject_id)->first();
        $meeting_id=$subject->meeting_id;
        $meeting=Meeting::where('id',$meeting_id)->first();
        $organization_id= $meeting->organization_id;
        //dd($organization_id);
       // return view('meetings.moveTo')->with ('meetings',Meeting::all())->with('subject_id',$subject_id);
        return view('meetings.moveTo')->with ('meetings',Meeting::where('organization_id',$organization_id)->get())->with('subject_id',$subject_id);

    }


    public function moveToThisMeeting($meeting_id,$subject_id)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to update the status..");
        }
       $id_subject=$subject_id;
       $id_meeting= $meeting_id;
       $subject = Subject::where('id',$id_subject)->firstOrFail();
       $subject->meeting_id=$id_meeting;
       $subject->save(); 
    
       $id_user = Auth::id();
       $user= User::where('id', $id_user)->firstOrFail();
       $organization_id=$user->organization_id;
       return view('meetings.index')->with ('meetings',Meeting::where('organization_id',$organization_id)->get())->with('successMsg','The subject has been moved  .');
    } 

    
    public function store($meeting_id,Request $request)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to update the status..");
        }
        $subject=new Subject();
        $id = Auth::id();
        $subject->meeting_id= $meeting_id;
        $subject->time_start=$request->time_start;
        $subject->time_end=$request->time_end;
        $subject->description=$request->description;
        $subject->status=0;
        $subject->save();
       
        $subjects = Subject::where('meeting_id', $meeting_id)->get();
        $tasks = Task::where('meeting_id', $meeting_id)->get();
        return redirect(route('meetingTasks',[$meeting_id] ));

    }

   
    public function show($id)
    {
        
    }

   
    public function edit(Subject $subject)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to edit this subjec..");
        }
        return view('subjects.create')->with('subject', $subject);
    }

   
    public function update(UpdateSubjectsRequest $request,Subject $subject)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to update the status..");
        }
        $subject->update($request->except(['_token']));
        if ($request->ajax()){
            return Response::json(array('result'=>'success', 'status'=>$request->status),200);
        }
        $subject->description=$request->description;
        $subject->save();
        return redirect(route('subjects.index')); 
    }

    public function destroy(Subject $subject)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to delete this subjec..");
        }
        $subject->delete();
        return redirect(route('meetings.index'));
    }
    
}

resources/views/subjects/create.blade.php
@extends('layouts.app')
@section('content')

<div class ="card card -default">
    <div class="card-header">
    {{isset($subject)? "Edit Subject " :"Create New Subject" }}
    </div>
    <div class="card-body">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul class="list-group">
            @foreach ($errors->all() as $error)
                <li class="list-group-item text-danger">
                {{ $error }}
                </li>
            @endforeach
        </ul>
    </div>
    @endif

   <form method="POST" action="{{isset($subject)?route('subjects.update',$subject->id): route('subjects-store',[$meeting_id])}}">
     {{csrf_field()}}
     @if(isset($subject))
      @method('PUT')
     @endif 

      <div class="form-group">
       <label for="description">Description</label>
       <input type="text" id="description" class="form-control" name="description" value="{{isset($subject) ? $subject->description :''}}">
      </div>

      <div class="form-group">
       <label for="time_start">Time Start </label>
       <input type="datetime-local" id="time_start" class="form-control" name="time_start" value="{{isset($subject) ? $subject->time_start :''}}"required>
      </div>    

      <div class="form-group">
       <label for="time_end">Time End </label>
       <input type="datetime-local" id="time_end" class="form-control" name="time_end" value="{{isset($subject) ? $subject->time_end :''}}"required>
      </div> 

      <div class="form-group">
       <button class="btn btn-success">
       {{isset($subject)?'Update Subject' : 'Add New Subject'}}
       </button>
      </div>
     </form>
   </div>
</div>    
@endsection

resources/views/subjects/index.blade.php
@extends('layouts.app')
@section('content')

<div class ="d-flex justify-content-end mb-2">
    <a href ="{{route('subjects.create')}}"class="btn btn-success">Add New Subject</a>
</div>

<div class ="card card -default">
    <div class="card-header">subjects</div>
     <div class = "card-body">
      <table class="table">
       <thead>
       <th>Subjects Description</th>
        <th>Subjects Start</th>
        <th>Subjects End</th>
        <th>Status</th>
        <th></th>
       </thead>

       <tbody>
        @foreach($subjects as $subject)
         <tr>
          <td>{{$subject->description}}</td>
          <td>{{$subject->subject_start}}</td>
          <td>{{$subject->subject_end}}</td>
          <td>{{$subject->status}}</td>
          <td> <a href ="{{route('subjects.edit',$subject->id)}}" class="btn btn-info btn-sm">Edit</a></td>
          </tr>
        @endforeach 
       </tbody>
      </thead>
            
     </div>   
</div>
@endsection