routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home','HomeController@index')->name('home');
Route::post('/tasks-store/{meeting_id?}','TaskController@store')->name('tasks-store');
Route::post('/subjects-store/{meeting_id?}','SubjectController@store')->name('subjects-store');
Route::get('tasks/done/{id}', 'TaskController@done')->name('done');
Route::get('tasks/donelate/{id}', 'TaskController@donelate')->name('donelate');
Route::get('tasks/discussed/{id}','TaskController@discussed')->name('discussed');
Route::resource('/employees','EmployeesController')->middleware('auth');
Route::get('/MyMeetings','MeetingController@indexMy')->name('MyMeetings');

Route::resource('/meetings','MeetingController')->middleware('auth');
Route::get('/sendemail', 'SendEmailController@index')->name('sendemail');
Route::post('/sendemail/send', 'SendEmailController@send');

Route::resource('/dashboards','DashboardController')->middleware('auth');

Route::resource('/tasks','TaskController')->except(['store']);
Route::resource('/subjects','SubjectController')->except(['store']);
Route::get('tasks/{meeting_id}','TaskController@store');
Route::get('meetings/{organization_id}','MeetingController@store');
Route::get('subjects/{meeting_id}','SubjectController@store');

Route::get('tasks/meetingTasks/{meeting_id}','TaskController@meetingTasks')->name('meetingTasks');
Route::get('/newOne', function () { return view('newOne');})->name('newOne');

Route::get('/moveTo/{id?}','SubjectController@moveTo')->name('moveTo');
Route::get('/moveToThisMeeting/{id?}/{subject_id}','SubjectController@moveToThisMeeting')->name('moveToThisMeeting');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable =[
        'title','task_user_id','task_start','tsak_end'
    ];

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function meeting(){
        return $this->belongsTo('App\Meeting');
    }

}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Meeting;
use App\User;
use App\Task;
use App\Subject;
use App\Organization;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Tasks\CreatTaskRequest;
use App\Http\Requests\Tasks\UpdateTasksRequest;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;


class TaskController extends Controller
{
    
    public function index()
    {
     return view('tasks.index')->with ('tasks',Task::all());   
    }

    public function meetingTasks($meeting_id)
    {
       $id=$meeting_id;
       $subjects = Subject::where('meeting_id', $id)->get();
       $tasks = Task::where('meeting_id', $id)->get();
       return view('tasks.meetingTasks',compact('tasks', 'subjects', 'meeting_id'));
    }   

    
    public function create(Request $request)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to create new Task..");
        }
        $meeting_id = $request->get('meeting_id');
        return view('tasks.create')->with('meeting_id', $meeting_id);
    }

    public function store($meeting_id, Request $request)
    {
        //dd($request);
        $task=new Task();
        $id = Auth::id();
        $task->title=$request->title;
        $task->task_user_id=$request->task_user_id;
        $task->meeting_id= $meeting_id;
        $task->task_start=$request->task_start;
        $task->task_end=$request->task_end;
        $task->status=0;
        $task->save();
        $subjects = Subject::where('meeting_id', $meeting_id)->get();
        $tasks = Task::where('meeting_id', $meeting_id)->get();
        return redirect(route('meetingTasks',[$meeting_id] ));
         
    }
 
   
    public function show($id)
    {
        //
    }

    
    public function edit(Task $task)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to edit this Task..");
        }
        return view('tasks.create')->with('task', $task);
        
    }
    
    public function update(UpdateTasksRequest $request,Task $task)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to update this Task..");
        }
        $task->title=$request->title;
        $task->save();
        return redirect(route('tasks.index')); 
    }

    
    public function destroy(Task $task)
    {
        if (Gate::allows('participant')) {
            abort(403,"Sorry you are not allowed to delete this Task..");
        }
        $task->delete();
        return redirect(route('meetings.index'));
    }
    public function done($id)
    { 
        
        $task = Task::findOrFail($id);
       // dd($task)    ;        
        $task->status = 1; 
        $task->save();
        $meeting_id=$task->meeting_id;
        $subjects = Subject::where('meeting_id',$meeting_id)->get();
        $tasks = Task::where('meeting_id', $meeting_id)->get();
        return view('tasks.meetingTasks', compact('tasks','subjects','meeting_id')); 
    }
    public function donelate($id)
    { 
        $task = Task::findOrFail($id);
       // dd($task)    ;        
        $task->status = 2; 
        $task->save();
        $meeting_id=$task->meeting_id;
        $subjects = Subject::where('meeting_id',$meeting_id)->get();
        $tasks = Task::where('meeting_id', $meeting_id)->get();
        return view('tasks.meetingTasks', compact('tasks','subjects','meeting_id')); 
    }
    public function discussed($id)
    { 
        
        $subject = Subject::findOrFail($id);
       // dd($task)    ;        
        $subject->status = 1; 
        $subject->save();
        $meeting_id=$subject->meeting_id;
        $subjects = Subject::where('meeting_id',$meeting_id)->get();
        $tasks = Task::where('meeting_id', $meeting_id)->get();
        return view('tasks.meetingTasks', compact('tasks','subjects','meeting_id')); 
    }
    

    
    /*public function destroy($id)
    {
        $task = Task::find($id);
        $meeting_id=$task->meeting_id;
        $subjects = Subject::where('meeting_id',$meeting_id)->get();
        $tasks = Task::where('meeting_id',$meeting_id)->get();
        $task->delete();
        //dd($meeting_id);
        return view('tasks.meetingTasks', compact('tasks','subjects','meeting_id')); 
    }*/
}

resources/views/tasks/create.blade.php
@extends('layouts.app')
@section('content')

<div class ="card card -default">
    <div class="card-header">
    {{isset($task)? "Edit Task " :"Create New Task" }}
    </div>
    <div class="card-body">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul class="list-group">
            @foreach ($errors->all() as $error)
                <li class="list-group-item text-danger">
                {{ $error }}
                </li>
            @endforeach
        </ul>
    </div>
    @endif
   <form method="POST" action="{{isset($task)?route('tasks.update',$task->id) : route('tasks-store',[$meeting_id])}}">
     {{csrf_field()}}
     @if(isset($task))
      @method('PUT')
     @endif 


      <div class="form-group">
       <label for="title">Task</label>
       <input type="text" id="title" class="form-control" name="title" value="{{isset($task) ? $task->title :''}}">
      </div> 
      
        {{-- <input type="hidden" value="{{$meeting_id}}" name="meeting_id_from_hidden_input"> --}}
      
      <div class="form-group">
       <label for="task_user_id">Responsible Task (id of employees)</label>
       <input type="number" id="task_user_id" class="form-control" name="task_user_id" value="{{isset($task) ? $task->task_user_id :''}}" required>
      </div> 
      
      <div class="form-group">
       <label for="task_start">Task Start </label>
       <input type="datetime-local" id="task_start" class="form-control" name="task_start" value="{{isset($task) ? $task->task_start :''}}"required >
      </div>    

      <div class="form-group">
       <label for="task_end">Task End </label>
       <input type="datetime-local" id="task_end" class="form-control" name="task_end" value="{{isset($task) ? $task->task_end :''}}"required >
      </div> 

      <div class="form-group">
       <button class="btn btn-success">
       {{isset($task)?'Update Task' : 'Add Task'}}
       </button>
      </div>
     
     </form>
   </div>
</div>    
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')
@section('content')
@cannot('participant')
<div class ="d-flex justify-content-end mb-2">
    <a href ="{{route('tasks.create')}}"class="btn btn-success">Add New Task</a>
</div>
@endcannot
<div class ="card card -default">
    <div class="card-header">tasks</div>
     <div class = "card-body">
      <table class="table">
       <thead>
        <th>Task Title</th>
        <th>Meeting Name</th>
        <th>Task start</th>
        <th>Task end</th>
        <th>Status</th>
        <th></th>
        
       </thead>
       <tbody>
        @foreach($tasks as $task)
        @if ((Auth::user()->id)==($task->task_user_id))
         <tr>
         <td>{{$task->title}}</td>
          <td>{{$task->meeting_id}}</td>
          <td>{{$task->task_start}}</td>
          <td>{{$task->task_end}}</td>
          <td>
            @if (($task->status==0)&(date('Y-m-d H:i:s') < $task->task_end) )
              <a href="{{route('done',$task->id)}}">Mark As done</a>
            @elseif(($task->status==0)&(date('Y-m-d H:i:s') > $task->task_end) )
              <a href="{{route('donelate',$task->id)}}">Mark As done late </a>
            @elseif($task->status==2)
             <font color="red">Task was completed late</font>
            @else
              Task Done.
            @endif
          </td>
          @cannot('participant')
          <td> <a href ="{{route('tasks.edit',$task->id)}}" class="btn btn-info btn-sm">Edit</a></td>
         @endcannot
          </tr>
        
        @endif  
        @endforeach 
       </tbody>
      </thead>
            
     </div>   
</div>
@endsection

resources/views/tasks/meetingTasks.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
@cannot('participant')
<div class ="d-flex justify-content-end mb-2">
 <a href ="{{route('subjects.create',['meeting_id'=>$meeting_id])}}" class="btn btn-success">Add New Subject</a>
</div>
@endcannot
<h5><span class="badge badge-dark">Meeting number : {{$meeting_id}}</span></h5><br>
<div class ="card card -default">
    <div class="card-header">subject</div>
     <div class = "card-body">
      <table class="table">
       <thead>
        <th>Subjects Description</th>
        <th>Subjects Start</th>
        <th>Subjects End</th>
        @cannot('participant')
        <th>Status</th>
        @endcannot
        <th></th>
        <th></th>
        <th></th>
       </thead>

       <tbody>
       <?php
          date_default_timezone_set('Asia/Jerusalem')
       ?>
        @foreach($subjects as $subject)
         <tr>
          <td>{{$subject->description}}</td>
          <td>{{$subject->time_start}}</td>
          <td>{{$subject->time_end}}</td>
          @cannot('participant')
          <td>
            @if(($subject->status==0)&(date('Y-m-d H:i:s') > $subject->time_start)&(date('Y-m-d H:i:s') < $subject->time_end))
              <a href="{{route('discussed',$subject->id)}}">Mark As discussed</a>
            @elseif (($subject->status==0)&(date('Y-m-d H:i:s') > $subject->time_end))
             <font color="red">Subject Not Discussed</font>
            @elseif($subject->status==1)
            <font color="green">Subject Discussed</font>
              
            @else
              Meeting has not started
            @endif
            </td>
            @endcannot
          <td><a href ="{{route('subjects.edit',$subject->id)}}" class="btn btn-info btn-sm">Edit</a></td>
          @cannot('participant')
    <td><a href ="{{route('moveTo',$subject->id)}}" class="btn btn-info btn-sm">move to other meeting</a></td>
    @endcannot
          <td>
          <form method="post" action ="{{action('SubjectController@destroy',$subject->id)}}">
          @csrf
          @method('DELETE')
            <input type ="submit" class=" btn btn-danger btn-sm" name="submit" value ="Delete"> 
          </form>
          </td>
         </tr>
        @endforeach 
        </tbody>
      </table>
                
     </div>   
    </div><br><br>
@cannot('participant')  
<div class ="d-flex justify-content-end mb-2">
    <a href ="{{route('tasks.create',['meeting_id'=>$meeting_id])}}"class="btn btn-success">Add New Task</a>
</div>
@endcannot

<div class ="card card -default">
    <div class="card-header">tasks</div>
     <div class = "card-body">
      <table class="table">
       <thead>
        <th>Task Title</th>
        <th>Task start</th>
        <th>Task end</th>
        <th>Status</th>
        <th></th>
        <th></th>
        <th></th>
       </thead>

       <tbody>
        @foreach($tasks as $task)
         <tr>
          <td>{{$task->title}}</td>
          <td>{{$task->task_start}}</td>  
          <td> {{$task->task_end}} </td>
          <td>
            @if (($task->status==0)&(date('Y-m-d H:i:s') < $task->task_end) )
              <a href="{{route('done',$task->id)}}">Mark As done</a>
            @elseif(($task->status==0)&(date('Y-m-d H:i:s') > $task->task_end) )
              <a href="{{route('donelate',$task->id)}}">Mark As done late </a>
            @elseif($task->status==2)
             <font color="red">Task was completed late</font>
            @else
              Task Done.
            @endif
          </td>
          <td><a href ="{{route('tasks.edit',$task->id)}}" class="btn btn-info btn-sm">Edit</a></td>
          <td>
          <form method="post" action ="{{action('TaskController@destroy',$task->id)}}">
          @csrf
          @method('DELETE')
            <input type ="submit" class=" btn btn-danger btn-sm" name="submit" value ="Delete"> 
          </form>
          </td>
         </tr>
        @endforeach 
       </tbody>
      </table>
            
     </div>   
</div>
</div>
@endsection