routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home','HomeController@index')->name('home');
Route::post('/tasks-store/{meeting_id?}','TaskController@store')->name('tasks-store');
Route::post('/subjects-store/{meeting_id?}','SubjectController@store')->name('subjects-store');
Route::get('tasks/done/{id}', 'TaskController@done')->name('done');
Route::get('tasks/donelate/{id}', 'TaskController@donelate')->name('donelate');
Route::get('tasks/discussed/{id}','TaskController@discussed')->name('discussed');
Route::resource('/employees','EmployeesController')->middleware('auth');
Route::get('/MyMeetings','MeetingController@indexMy')->name('MyMeetings');

Route::resource('/meetings','MeetingController')->middleware('auth');
Route::get('/sendemail', 'SendEmailController@index')->name('sendemail');
Route::post('/sendemail/send', 'SendEmailController@send');

Route::resource('/dashboards','DashboardController')->middleware('auth');

Route::resource('/tasks','TaskController')->except(['store']);
Route::resource('/subjects','SubjectController')->except(['store']);
Route::get('tasks/{meeting_id}','TaskController@store');
Route::get('meetings/{organization_id}','MeetingController@store');
Route::get('subjects/{meeting_id}','SubjectController@store');

Route::get('tasks/meetingTasks/{meeting_id}','TaskController@meetingTasks')->name('meetingTasks');
Route::get('/newOne', function () { return view('newOne');})->name('newOne');

Route::get('/moveTo/{id?}','SubjectController@moveTo')->name('moveTo');
Route::get('/moveToThisMeeting/{id?}/{subject_id}','SubjectController@moveToThisMeeting')->name('moveToThisMeeting');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
  
    

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
        @auth
        <div class="container">
         <div class="row">
          <div class ="col-md-2">
           <ul class="list-group">
            <li class ="list-group-item">
             <a href ="{{route('meetings.index')}}">Organization Meetings</a>
            </li>
            <li class ="list-group-item">
             <a href ="{{route('MyMeetings')}}">MY  Meetings</a>
            </li>
            <li class ="list-group-item">
             <a href ="{{route('tasks.index')}}">My Tasks</a> 
            </li> 
            <li class ="list-group-item">
             <a href ="{{route('employees.index')}}">Organization employees</a> 
            </li>
            @can('admin') 
            <li class ="list-group-item">
             <a href ="{{route('sendemail')}}">Send invitation by Email </a> 
            </li> 
            @endcan
            @cannot('participant')
            <li class ="list-group-item">
             <a href ="{{route('dashboards.index')}}">Dashboard</a> 
            </li>
            @endcannot
           </ul> 
          </div>
          <div class ="col-md-10">
          @yield('content')
          </div>
         </div>
        </div> 
        @else
            @yield('content')
        @endauth
        </main>
    </div>
    @yield('scripts')
</body>
</html>